
{# Autogenerated by prophecy #}
{% macro prophecy_tmp_source(pipelineName, label, suffix = '') %}
    {% set tmp_table = "prophecy_tmp__" ~ var('prophecy_run_id', 'default_run_id') ~ "__" ~ pipelineName ~ "__" ~ label %}

    {% if suffix != '' %}
        {% set tmp_table = tmp_table ~ "_" ~ suffix %}
    {% endif %}

    {% set table_name = adapter.quote(target.database) ~ "." ~ adapter.quote(target.schema) ~ "." ~ adapter.quote(tmp_table) %}
    {{ return(table_name) }}
{% endmacro %}
